spring.application.name=NotificationServiceQuickBite
server.port=8086

# Base de datos autom�tica
spring.datasource.url=jdbc:mysql://localhost:3306/quickbite_notifications?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuraci�n de Servidor de Email (Ejemplo gen�rico/falso para pruebas con Mailtrap o Mailhog)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=tu_usuario_de_pruebas
spring.mail.password=tu_contrase�a_de_pruebas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true